name: Lee Eric Smith
favicon: null
layout_spectrum: 0.9565309074241668
typography_spectrum: 0.680908058071509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.22347538056783378
  lightness: 0.5651765903457999
  saturation: 0.4189834997523576
  rhythmicContrast: 0.1029254556633532
purpose: []
